# Generated by Django 6.0.3 on 2026-03-05 14:59

from django.db import migrations, models

import dj_advertisers.fields

CREATE_ENUMS = """
CREATE TYPE monetizationtype AS ENUM ('CPC', 'CPA');
CREATE TYPE billingsource AS ENUM ('INTERNAL', 'PARTNER');
CREATE TYPE timezone AS ENUM ('UTC', 'EST', 'CST', 'PST');
"""

DROP_ENUMS = """
DROP TYPE IF EXISTS monetizationtype;
DROP TYPE IF EXISTS billingsource;
DROP TYPE IF EXISTS timezone;
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunSQL(CREATE_ENUMS, DROP_ENUMS),
        migrations.CreateModel(
            name="Advertiser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=4, default=0, max_digits=5
                    ),
                ),
                (
                    "default_conversion_rate",
                    models.DecimalField(
                        decimal_places=4, default=0.01, max_digits=6
                    ),
                ),
                (
                    "monetization_type",
                    dj_advertisers.fields.PostgreSQLEnumField(
                        choices=[("CPC", "CPC"), ("CPA", "CPA")],
                        default="CPC",
                        enum_name="monetizationtype",
                        max_length=20,
                    ),
                ),
                (
                    "billing_source",
                    dj_advertisers.fields.PostgreSQLEnumField(
                        choices=[
                            ("INTERNAL", "Internal"),
                            ("PARTNER", "Partner"),
                        ],
                        default="INTERNAL",
                        enum_name="billingsource",
                        max_length=20,
                    ),
                ),
                (
                    "billing_timezone",
                    dj_advertisers.fields.PostgreSQLEnumField(
                        choices=[
                            ("UTC", "UTC"),
                            ("EST", "Eastern"),
                            ("CST", "Central"),
                            ("PST", "Pacific"),
                        ],
                        default="UTC",
                        enum_name="timezone",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
